CREATE TABLE IF NOT EXISTS cars (
id BIGINT PRIMARY KEY AUTO_INCREMENT,
model VARCHAR(255) NOT NULL,
brand VARCHAR(255) NOT NULL,
inventory INT NOT NULL,
car_type ENUM('SEDAN', 'SUV', 'HATCHBACK', 'UNIVERSAL') NOT NULL,
daily_fee DECIMAL(10, 2) NOT NULL
);
